name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions black flake8 isort
    - name: Sort imports with isort
      run: isort --check --line-length 80 --profile black src/ && isort --check --line-length 80 --profile black test/
    - name: Format with black
      run: black --check src/ && black --check test/
    - name: Lint with flake8
      run: flake8 src/ && flake8 test/
    - name: Test with tox
      run: tox --develop